
import matplotlib.pyplot as plt

# Matplotlib settings
dict_rc = {
    'axes.grid': True,
    'axes.linewidth': 0.6,
    'axes.titlepad': 5.0,
    'errorbar.capsize': 3.0,
    'figure.figsize': [4, 4],
#     'figure.facecolor': 'f4f4f4',
    'figure.titleweight': 'bold',
    'font.serif': [
        'TeX Gyre Schola',
        'TeX Gyre Bonum',
        'TeX Gyre Termes',
        'TeX Gyre Pagella',
        'DejaVu Serif',
        'Bitstream Vera Serif',
        'Computer Modern Roman',
        'Bookman',
        'Century Schoolbook L',
        'Charter',
        'ITC Bookman',
        'New Century Schoolbook',
        'Nimbus Roman No9 L',
        'Palatino',
        'Times New Roman',
        'Times',
        'Utopia',
        'serif',
    ],
    'font.sans-serif': [
        'TeX Gyre Heros',
        'DejaVu Sans',
        'Bitstream Vera Sans',
        'Computer Modern Sans Serif',
        'Arial',
        'Avenir',
        'Fira Math',
        'Frutiger',
        'Geneva',
        'Gill Sans',
        'Helvetica',
        'Lucid',
        'Lucida Grande',
        'Myriad Pro',
        'Noto Sans',
        'Roboto',
        'Source Sans Pro',
        'Tahoma',
        'Trebuchet MS',
        'Ubuntu',
        'Univers',
        'Verdana',
        'sans-serif',
    ],
    'font.monospace': [
        'TeX Gyre Cursor',
        'DejaVu Sans Mono',
        'Bitstream Vera Sans Mono',
        'Computer Modern Typewriter',
        'Andale Mono',
        'Courier New',
        'Courier',
        'Fixed',
        'Nimbus Mono L',
        'Terminal',
        'monospace',
    ],
    'font.cursive': [
        'TeX Gyre Chorus',
        'Apple Chancery',
        'Felipa',
        'Sand',
        'Script MT',
        'Textile',
        'Zapf Chancery',
        'cursive',
    ],
    'font.fantasy': [
        'TeX Gyre Adventor',
        'Avant Garde',
        'Charcoal',
        'Chicago',
        'Comic Sans MS',
        'Futura',
        'Humor Sans',
        'Impact',
        'Optima',
        'Western',
        'xkcd',
        'fantasy',
    ],
    'font.size': 9.0,
    'grid.alpha': 0.1,
    'grid.color': 'black',
    'grid.linewidth': 0.6,
    'hatch.linewidth': 0.6,
    'legend.borderaxespad': 0,
    'legend.borderpad': 0.5,
    'legend.columnspacing': 1.5,
    'legend.edgecolor': 'black',
    'legend.facecolor': 'white',
    'legend.fancybox': False,
    'legend.handletextpad': 0.5,
    'mathtext.fontset': 'custom',
    'mathtext.default': 'regular',
    'patch.linewidth': 0.6,
#     'savefig.dpi': 1000,
    'savefig.facecolor': 'white',
#     'savefig.format': 'pdf',
    'xtick.major.pad': 2.0,
    'xtick.major.size': 4.0,
    'xtick.major.width': 0.6,
    'xtick.minor.pad': 2.0,
    'xtick.minor.width': 0.48,
    'xtick.minor.visible': True,
    'ytick.major.pad': 2.0,
    'ytick.major.size': 4.0,
    'ytick.major.width': 0.6,
    'ytick.minor.pad': 2.0,
    'ytick.minor.width': 0.48,
    'ytick.minor.visible': True,
    'axes.titlecolor': 'black',
#     'xtick.labelcolor': 'black',
#     'ytick.labelcolor': 'black',
}

# Apply the above matplotlib settings
for k, v in dict_rc.items():
    plt.rcParams[k] = v